export const ADD_OSCILLATOR = 'ADD_OSCILLATOR';
export const REMOVE_OSCILLATOR = 'REMOVE_OSCILLATOR';
export const SET_OSCPARAM = 'SET_OSCPARAM';
export const ADD_EFFECT = 'ADD_EFFECT';
export const REMOVE_EFFECT = 'REMOVE_EFFECT';
export const SET_EFFECTPARAM = 'SET_EFFECTPARAM';
